version: '3.9'

services:
  client:
    image: utsubo-site-client
    container_name: utsubo-site-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - '.:/usr/src/app'
    tty: true
    stdin_open: true
